sudo: required

# safelist
branches:
  only:
  - master

services:
  - docker

before_install:
  - docker network create -d bridge --subnet 172.25.0.0/16 maisie_nw
  - docker run -itd --name postgres --network maisie_nw postgres
  - docker build -t shon3005/multi-maisie-test -f ./maisie_api/Dockerfile.dev ./maisie_api

script:
  - docker run --network maisie_nw -e SENDGRID_API_KEY=$SENDGRID_API_KEY -e SENDGRID_TEMPLATE_ID=$SENDGRID_TEMPLATE_ID -e "MAISIE_ORIGIN=http://localhost:3000" -e "PGUSER=postgres" -e "PGPASSWORD=postgres_password" -e "PGDATABASE=maisie_api_test" -e "PGHOST=postgres" -e "PGPORT=5432" shon3005/multi-maisie-test mix test

after_success:
  - docker build -t shon3005/multi-maisie-nginx ./nginx
  - docker build -t shon3005/multi-maisie-api ./maisie_api
  - docker build -t shon3005/multi-maisie-site ./maisie_site
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push shon3005/multi-maisie-nginx
  - docker push shon3005/multi-maisie-api
  - docker push shon3005/multi-maisie-site

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-maisie-docker
  env: Maisie-App-env
  bucket_name: elasticbeanstalk-us-east-1-640883773139
  bucket_path: multi-maisie-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY