version: '3'
services:
  postgres:
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/usr/local/var/postgres
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '4000:80'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./maisie_api
    volumes:
      - /app/deps
      - ./maisie_api:/app
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=maisie_api_dev
      - PGPASSWORD=postgres_password
      - PGPORT=5432
      - GUARDIANSECRET=8IW0WCEymrsSAXKoRpyEzZwx5FLEHQx2BepmCo9d9JoY8dsuBh8942muHr7NhIca
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./maisie_site
    volumes:
      - /app/node_modules
      - ./maisie_site:/app
    environment:
      - API=api
volumes:
  postgres-data:
