FROM elixir:latest
WORKDIR "/app"
RUN mix local.hex --force
RUN mix local.rebar --force
COPY ./mix.exs ./mix.lock ./
RUN mix do deps.get, deps.compile
COPY . .
CMD mix ecto.create && mix ecto.migrate && mix phx.server