FROM bitwalker/alpine-elixir-phoenix:latest
WORKDIR "/app"
COPY ./mix.exs ./mix.lock ./
# , deps.compile
RUN mix do deps.get
COPY ./priv ./config ./entrypoint.sh ./
RUN ["chmod", "+x", "./entrypoint.sh"]
ENTRYPOINT ["sh", "./entrypoint.sh"]
COPY . .
CMD mix phx.server