# FROM bitwalker/alpine-elixir-phoenix:latest
FROM elixir:1.6.5-alpine
WORKDIR "/app"
COPY ./mix.exs ./mix.lock ./
RUN mix do deps.get
COPY ./priv ./config ./entrypoint.sh ./
RUN ["chmod", "+x", "./entrypoint.sh"]
ENTRYPOINT ["sh", "./entrypoint.sh"]
COPY . .
CMD mix phx.server